export const PortfolioSectionOrder = [
  'introduction',
  'intrpduction',
  'total experiance',
  'total experience',
  'education',
  'experiance',
  'experience',
  'project',
  'projects',
  'skill',
  'skills',
  'other',
  'others',
];